spring:
  # yml配置文件的方式是, 相同的部分能够用缩进的形式实现.
  # 配置数据源信息 等价于 spring.datasource.type=com.zaxxer.hikari.HikariDataSource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库的信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_code?characterEncoding=utf-8&userSSL=false
    username: root
    password: root

# 配置 MyBatisPlus 相关文件
mybatis-plus:
  configuration:
    # 配置日志输出功能 -> StdOutImpl是框架自带的
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl















