spring:
  # yml配置文件的方式是, 相同的部分能够用缩进的形式实现.
  # 配置数据源信息 等价于 spring.datasource.type=com.zaxxer.hikari.HikariDataSource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置连接数据库的信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_code?characterEncoding=utf-8&userSSL=false
    username: root
    password: root

# 配置 MyBatisPlus 相关文件
mybatis-plus:
  configuration:
    # 配置日志输出功能 -> StdOutImpl是框架自带的
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置MyBatis-Plus的全局设置
  global-config:
    db-config:
      # 设置所有表名对应的前缀
      table-prefix: t_
      # 设置统一的主键生成策略, 避免在每个类上都加上TableId注解. 如果是NONE, 那么插入数据之后不会将id返回给实体对象
      id-type: AUTO
  # 用来自动设置别名, 以包为单位. 包下的Bean都会被自动起别名. 例: User -> User | user 均可
  type-aliases-package: com.atguigu.mybatisplus.pojo















